["good first issue"]
color = "7057ff"
name = "good first issue"
description = "Good for newcomers"

["help wanted"]
color = "008672"
name = "help wanted"
description = "Extra attention is needed"

[invalid]
color = "e4e669"
name = "invalid"
description = "This doesn't seem right"

[question]
color = "d876e3"
name = "question"
description = "Further information is requested"

[wontfix]
color = "ffffff"
name = "wontfix"
description = "This will not be worked on"
